import Head from 'next/head';
import Script from 'next/script';
import { PostCard, Categories, PostWidget } from '../components/index';

const posts = [
  { title: "Useful Chrome Extensions that you shouldn't miss out on", excerpt: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores excepturi doloribus consequuntur accusamus nihil, ab rem! Quo quam iusto distinctio saepe facere quaerat nulla dolores perspiciatis tempore totam.' },
  { title: 'React Testing', excerpt: 'Learn React Testing' },
  { title: 'React with Tailwind', excerpt: 'Learn React with Tailwind' },
];

export default function Home() {
  return (
    <div className='container mx-auto'>
      <Head>
        <title>Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js' integrity='sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa' crossOrigin='anonymous'/>

      <div className='row'>
        <div className='col-md-8'>
          {posts.map((post, index) => (
            <PostCard post={post} key={post.title}/>
          ))}
        </div>
        <div className='col-md-3'>
          <PostWidget/>
          <Categories/>
        </div>
      </div>
    </div>
  )
}
